module.exports={
    HOST:"localhost",
    USER:"postgres",
    PASSWORD:"Sid@7710",
    DB:"api",
    dialect:"postgres",
    pool:{
        max:5,
        min:0,
        acquire:30000,
        idle:10000
    }
};